name: Publish to NuGet

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Extract Version From Tag
      id: get_version
      run: |
        # Takes 'v1.0.2' and strips the 'v' to get '1.0.2'
        TAG_NAME="${{ github.event.release.tag_name }}"
        VERSION="${TAG_NAME#v}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build and Pack
      run: |
        dotnet build --configuration Release /p:Version=${{ steps.get_version.outputs.version }}
        dotnet pack --configuration Release --output ./nupkg /p:Version=${{ steps.get_version.outputs.version }}

    - name: Push to NuGet
      run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source nuget.org

    # Optional: Automatically updates the published GitHub release text with the generated notes
    - name: Generate Release Notes in GitHub
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true